version: 1.0

port: 9091
use_https: true
use_path: true

logging:
  level: "info"
  console: false # printing log to console is only supported in development mode

server_chain:
  id: "0afc093ffb509f059c55478bc1a60351cef7b4e9c008a53a6cc8241ca8617dfe"
  signature_scheme: "bls0chain"

handlers:
  rate_limit: 0 # unlimited

worker:
  magic_block_worker: 5 # in seconds
