version: "3"
services:
  mongodb:
    image: mongo
    volumes:
      - ${VOLUMES_MONGO_DATA}:/data/db
    networks:
      default:
      testnet0:
    ports:
      - "27017:27017"
    labels:
      zchain: "mongo"
  0dns:
    environment:
      - DOCKER=true
    build:
      context: ../
      dockerfile: ./docker.local/Dockerfile
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
    volumes:
      - ${VOLUMES_CONFIG}:/0dns/config
      - ${VOLUMES_LOG}:/0dns/log
    ports:
      - "9091:9091"
    labels:
      zchain: "0dns"
    networks:
      default:
      testnet0:
        ipv4_address: 198.18.0.98
    command: ./bin/zdns --deployment_mode 0 --magic_block /0dns/config/magic_block.json

networks:
  default:
    driver: bridge
  testnet0:
    external: true

volumes:
  config:
  mongodata:
