version: "3"
services:
  0dns:
    environment:
      - DOCKER=true
    build:
      context: ../
      dockerfile: ./docker.local/Dockerfile
    volumes:
      - ./config:/0dns/config
      - ./0dns/log:/0dns/log
    ports:
      - "9091:9091"
    networks:
      default:
      testnet0:
        ipv4_address: 198.18.0.98
    command: ./bin/zdns --deployment_mode 0 --magic_block /0dns/config/magic_block.json

networks:
  default:
    driver: bridge
  testnet0:
    external: true

volumes:
  config:
