name: 0chain Build & Push Docker Image

on:
  workflow_dispatch:

env:
  ZCHAIN_DNS_REGISTRY: ${{ secrets.ZCHAIN_DNS_REGISTRY }}

jobs:
   zdns:
       name: "0dns"
       runs-on: [self-hosted, build]
       steps:
       - name: Set docker image tag
         id: get_info
         run: |
           if [[ "${{github.ref}}" == refs/pull/* ]]; then
           tag=${GITHUB_REF/\/merge/}
           echo "TAG=$(echo pr-${tag:10})" >> $GITHUB_ENV
           else
           echo "TAG=$(echo ${GITHUB_REF#refs/*/} | sed 's/\//-/g')" >> $GITHUB_ENV
           fi
           echo "BRANCH=$([ -z '${{ github.event.pull_request.head.sha }}' ] && echo ${GITHUB_REF#refs/*/} || echo $GITHUB_HEAD_REF)" >> $GITHUB_ENV
           echo "SHA=$([ -z '${{ github.event.pull_request.head.sha }}' ] && echo $GITHUB_SHA || echo '${{ github.event.pull_request.head.sha }}')" >> $GITHUB_ENV

       - uses: actions/checkout@v2

       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
            username: ${{ secrets.ZCHAIN_DOCKERHUB_USERNAME }}
            password: ${{ secrets.ZCHAIN_DOCKERHUB_PASSWORD }}

       - name: Build & Publish 0dns Docker Image
         run: |
            docker build -t zdns:latest -f "$DOCKERFILE_DNS" .
            docker tag zdns:latest $ZCHAIN_DNS_REGISTRY:$TAG
            docker push $ZCHAIN_DNS_REGISTRY:$TAG

            SHORT_SHA=$(echo ${{ env.SHA }} | head -c 8)
            docker tag zdns:latest $ZCHAIN_DNS_REGISTRY:$TAG-$SHORT_SHA
            docker push $ZCHAIN_DNS_REGISTRY:$TAG-$SHORT_SHA

         env:
           DOCKERFILE_DNS: "docker.local/Dockerfile"

       - name: Push latest
         if: ${{ github.ref == 'refs/heads/master' }}
         run: docker push $ZCHAIN_DNS_REGISTRY:latest
