name: Mirror repo to S3
on:
  push:
jobs:
  s3Backup:
    runs-on: docker-builds
    steps:
      - uses: actions/checkout@v1
      - name: Create backup
        run: |
          github-backup 0chain -P -t ${{ secrets.ACCESS_TOKEN }} --output-directory=/github-backup/0dns --all -O -R 0dns
          tar -zcvf /github-backup/0dns.tar.gz /github-backup/0dns
          rm -rf /github-backup/0dns
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: S3 Backup
        run: |
          aws s3 sync /github-backup/0dns.tar.gz s3://${{ secrets.MIRROR_TARGET }}/0dns.tar.gz
