name: Mirror repo to S3
on:
  push:
jobs:
  s3Backup:
    runs-on: docker-builds
    steps:
      - uses: actions/checkout@v2
      - name: S3 Backup
        uses: peter-evans/s3-backup@v1
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          MIRROR_TARGET: ${{ secrets.MIRROR_TARGET }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          STORAGE_SERVICE_URL: ${{ secrets.STORAGE_SERVICE_URL }}
        with:
          args: --overwrite --remove