name: Dockerize

on:
  workflow_dispatch:
    inputs:
      latest_tag:
        description: 'type yes for building latest tag'
        default: 'no'
        required: true

env:
  DNS_REGISTRY: 0dnsreg/0dns

jobs:
   dockerize_dns:
       runs-on: ubuntu-20.04
       steps:
       - uses: actions/checkout@v2

       - name: Get the version
         id: get_version
         run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)    

           # - name: Login to Docker Hub
           #   uses: docker/login-action@v1
           #   with:
           #     username: ${{ secrets.DOCKERHUB_USERNAME }}
           #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

       - name: Build zdns
         run: |
            docker build -t $DNS_REGISTRY:$TAG -f "$DOCKERFILE_DNS" .
            docker tag $DNS_REGISTRY:$TAG $DNS_REGISTRY:latest
         env:
           TAG: ${{ steps.get_version.outputs.VERSION }}
           DOCKERFILE_DNS: "docker.local/Dockerfile"

#        - name: Push image
#          run: |
#            if [[ "$PUSH_LATEST" == "yes" ]]; then
#              docker push $DNS_REGISTRY:latest
#            else
#              docker push $DNS_REGISTRY:$TAG
#            fi
#          env:
#            PUSH_LATEST: ${{ github.event.inputs.latest_tag }}
#            TAG: ${{ steps.get_version.outputs.VERSION }}
