name: build-&-publish-docker-image

on:
  push:
    branches: [ staging ]
  workflow_dispatch:
    inputs:
      latest_tag:
        description: 'type yes for building latest tag'
        default: 'no'
        required: true

env:
  DNS_REGISTRY: ${{ secrets.DNS_REGISTRY }}

jobs:
   dockerize_dns:
       runs-on: [self-hosted, build]
       steps:
       - uses: actions/checkout@v2

       - name: Get the version
         id: get_version
         run: |
            BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
            SHORT_SHA=$(echo $GITHUB_SHA | head -c 8)
            echo ::set-output name=BRANCH::${BRANCH}
            echo ::set-output name=VERSION::${BRANCH}-${SHORT_SHA}    

       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

       - name: Build 0dns Docker Image
         run: |
            docker build -t $DNS_REGISTRY:$TAG -f "$DOCKERFILE_DNS" .
            docker tag $DNS_REGISTRY:$TAG $DNS_REGISTRY:latest
            docker tag $DNS_REGISTRY:$TAG $DNS_REGISTRY:staging
            docker push $DNS_REGISTRY:$TAG
         env:
           TAG: ${{ steps.get_version.outputs.VERSION }}
           DOCKERFILE_DNS: "docker.local/Dockerfile"

       - name: Push 0dns Docker Image
         run: |
           if [[ "$PUSH_LATEST" == "yes" ]] && [[ "$BRANCH" == "master" ]]; then
             docker push $DNS_REGISTRY:latest
           elif [[ "$BRANCH" == "staging" ]]; then
             docker push $DNS_REGISTRY:staging
           fi
         env:
           PUSH_LATEST: ${{ github.event.inputs.latest_tag }}
           TAG: ${{ steps.get_version.outputs.VERSION }}
           BRANCH: ${{ steps.get_version.outputs.BRANCH }}
