name: build-&-publish-docker-image

concurrency:
  group: "publish-${{ github.ref }}"
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: [ staging ]
  workflow_dispatch:

env:
  DNS_REGISTRY: ${{ secrets.DNS_REGISTRY }}

jobs:
   dockerize_dns:
       runs-on: [self-hosted, build]
       steps:
       - name: Set docker image tag
         id: get_info
         run: |
           if [[ "${{github.ref}}" == refs/pull/* ]]; then
           tag=${GITHUB_REF/\/merge/}
           echo "TAG=$(echo pr-${tag:10})" >> $GITHUB_ENV
           else
           echo "TAG=$(echo ${GITHUB_REF#refs/*/} | sed 's/\//-/g')" >> $GITHUB_ENV
           fi
           echo "BRANCH=$([ -z '${{ github.event.pull_request.head.sha }}' ] && echo ${GITHUB_REF#refs/*/} || echo $GITHUB_HEAD_REF)" >> $GITHUB_ENV
           echo "SHA=$([ -z '${{ github.event.pull_request.head.sha }}' ] && echo $GITHUB_SHA || echo '${{ github.event.pull_request.head.sha }}')" >> $GITHUB_ENV

       - uses: actions/checkout@v2

       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

       - name: Build & Publish 0dns Docker Image
         run: |
            docker build -t $DNS_REGISTRY:$TAG -f "$DOCKERFILE_DNS" .
            docker tag $DNS_REGISTRY:latest $DNS_REGISTRY:$TAG
            docker push $DNS_REGISTRY:$TAG

            SHORT_SHA=$(echo ${{ env.SHA }} | head -c 8)
            docker tag $DNS_REGISTRY:latest $DNS_REGISTRY:$TAG-$SHORT_SHA
            docker push $DNS_REGISTRY:$TAG-$SHORT_SHA

         env:
           DOCKERFILE_DNS: "docker.local/Dockerfile"

       - name: Push latest
         if: ${{ github.ref == 'refs/heads/master' }}
         run: docker push $DNS_REGISTRY:latest

   system-tests:
     if: github.event_name != 'workflow_dispatch'
     needs: dockerize_dns
     runs-on: [ tests-suite ]
     steps:
       - name: "Get current PR"
         uses: jwalton/gh-find-current-pr@v1
         id: findPr
         with:
           github-token: ${{ github.token }}

       - name: "Set PR status as pending"
         uses: niteoweb/pull_request_status_action@v1.0.0
         if: steps.findPr.outputs.number
         with:
           pr_number: ${{ steps.findPr.outputs.pr }}
           description: "System tests running with default config..."
           state: "pending"
           repository: ${{ github.repository }}
           context: "0Chain System Tests"
           target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
         env:
           GITHUB_TOKEN: ${{ github.token }}

       - name: "Setup"
         run: |
           if [[ "${{github.ref}}" == refs/pull/* ]]; then
             tag=${GITHUB_REF/\/merge/}
             echo "TAG=$(echo pr-${tag:10})" >> $GITHUB_ENV
           else
             echo "TAG=$(echo ${GITHUB_REF#refs/*/} | sed 's/\//-/g')" >> $GITHUB_ENV
           fi

           echo "BRANCH=$([ -z '${{ github.event.pull_request.head.sha }}' ] && echo ${GITHUB_REF#refs/*/} || echo $GITHUB_HEAD_REF)" >> $GITHUB_ENV
           echo "SHORT_SHA=$(([ -z '${{ github.event.pull_request.head.sha }}' ] && echo $GITHUB_SHA || echo '${{ github.event.pull_request.head.sha }}') | head -c 8)" >> $GITHUB_ENV

           echo "NETWORK_URL=$(echo dev-${RUNNER_NAME:(-1)}.devnet-0chain.net)" >> $GITHUB_ENV
           echo "RUNNER_NUMBER=${RUNNER_NAME:(-1)}" >> $GITHUB_ENV

       - name: "Deploy 0Chain"
         uses: 0chain/actions/deploy-0chain@master
         with:
           kube_config: ${{ secrets[format('DEV{0}KC', env.RUNNER_NUMBER)] }}
           teardown_condition: "TESTS_PASSED"
           zdns_image: ${{ env.TAG }}-${{ env.SHORT_SHA }}
           miner_image:  staging
           sharder_image: staging
           blobber_image: staging
           validator_image: staging
           authorizer_image: staging
           zbox_image: staging
           zblock_image: staging
           explorer_image: latest
           zproxy_image: staging
           zsearch_image: staging
           blobber_stake_image: latest

       - name: "Run System tests"
         uses: 0chain/actions/run-system-tests@master
         with:
           system_tests_branch: master
           network: ${{ env.NETWORK_URL }}
           zbox_cli_branch: staging
           zwallet_cli_branch: staging
           smart_contract_owner_wallet_json: ${{ secrets.SMART_CONTRACT_OWNER_WALLET_JSON }}
           svc_account_secret: ${{ github.token }}
           deploy_report_page: false
           archive_results: true
           run_flaky_tests: false
           retry_failures: true

       - name: "Set PR status as ${{ job.status }}"
         if: ${{ (success() || failure()) && steps.findPr.outputs.number }}
         uses: niteoweb/pull_request_status_action@v1.0.0
         with:
           pr_number: ${{ steps.findPr.outputs.pr }}
           description: "System tests with default config"
           state: ${{ job.status }}
           repository: ${{ github.repository }}
           context: "0Chain System Tests"
           target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
         env:
           GITHUB_TOKEN: ${{ github.token }}